### ISSUE TITLE
'alias' / 'bind' Allow creation with invalid sound / alias

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/threebot#5]
The check for a valid sound seems to occur _somewhere_ but I haven't found it yet.

**Comment by codeandkey** [comment]
bind() only stores the bind string, it shouldn't be performing any checks like this; is it failing at bind() time or when the sound is played?

**Comment by codeandkey** [comment]
Fixed in 8542f83c

**Comment by codeandkey** [comment]
Also addressed a bit in 062fe230; now the 'name' command can be used for all sound aliasing with this check added.
